name: dotnet package

on: [push]

jobs:
  build:

    runs-on: [self-hosted, chen2584, chen2585]
    # strategy:
      # matrix:
        # dotnet-version: [ '5.0.x' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1.6.0
      with:
        dotnet-version: '5.0.101'
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Install dependencies
      run: dotnet restore src/MyWeb
    - name: Test
      run: dotnet test --no-restore src/MyWeb.Tests
    - name: Publish
      run: dotnet publish -c Release --no-restore -o .publish src/MyWeb
    - name: Zip file
      run: Compress-Archive -Path .publish/* -DestinationPath MyWeb.zip
    # - name: Archive Release
    #   uses: thedoctor0/zip-release@master
    #   with:
    #     path: '.publish'
    #     filename: 'MyWeb.zip'
    #     exclusions: '*.git*'
    - name: Upload Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: 'MyWeb.zip'
        tag: 0.1.0
        overwrite: true
        body: "This is my release text"